language:
  - java
jdk:
  - openjdk8
script:
- ./gradlew test
- docker build -t calculations .
- docker run -d -p 8080:8080 --name calculations_container calculations && sleep 10
- curl http://127.0.0.1:8080/v1/info
- docker stop calculations_container
- docker rm calculations_container
- docker rmi calculations
